country_name = {
    "Australia":"au",
    "Austria":"as",
    "Belgium":"bg",
    "Brazil":"br",
    "Canada":"ca",
    "Cyprus":"cyen",
    "Denmark":"dk",
    "Estonia":"ee",
    "Finland":"fi",
    "France":"fr",
    "Germany":"gr",
    "Greenland":"gl",
    "Hungary":"hu",
    "Iceland":"is",
    "Italy":"it",
    "Netherlands":"nl",
    "Norway":"no",
    "Poland":"pl",
    "Portugal":"pt",
    "Slovenia":"sl",
    "South Africa":"za",
    "Spain":"sp",
    "Sweden":"sw",
    "Switzerland":"sz",
    "Tunisia":"tn",
    "United Kingdom":"uk",
    "United States":"us",
    "Uruguay":"uy"

}
